### ISSUE TITLE
Swift 中，使用 UIScrollView 嵌套 UIScrollView 时，下拉刷新控件的问题

### ISSUE THREAD

**Issue by Ccmi** [HHHsiang/KafkaRefresh#57]
- iOS最新版本
- KafkaRefresh 最新版本
在一个 UIScrollView 中 嵌套另一个 UIScrollView 时；
父 ScrollView 设置代理；
子 ScrollView 的 isScrollEnabled 设为 false 且不设置代理；
在 scrollViewDidScroll 方法中通过监听父 ScrollView 的滚动来设置子 ScrollView 的 contentOffset 使其达到滚动的目的；
当父 ScrollView 的 contentOffset.y 为 < 0 时，子 ScrollView 的 contentOffset.y 也小于 0，但是刷新控件不会随子 ScrollView 显示出来;
尝试更换 MJRefresh 可以显示刷新控件；
希望作者可以解答；
相关效果 Demo 地址：https://github.com/seedotlee/AlipayIndexDemo

# ☕️  [赞助](https://github.com/OpenFeyn/KafkaRefresh/blob/master/sponsor.jpg)

**Comment by Ccmi** [comment]
![image](https://user-images.githubusercontent.com/17047142/59893342-38cead80-940f-11e9-9c16-129cfd2d88a4.png)
关键代码在于使用代码控制 contentOffset 时，scrollView.isDragging 是一直为 false ，所以无法进入任何分支

**Comment by OpenFeyn** [comment]
看起来累。怎不给视频

**Comment by Ccmi** [comment]
用 https://github.com/seedotlee/AlipayIndexDemo 这个 Demo ，然后将刷新控件换成 KafkaRefresh 就会出现问题。

**Comment by Ccmi** [comment]
https://camo.githubusercontent.com/54166fb0269627580639e78bcf9d7e83922f559d/687474703a2f2f6f64756d706e3776742e626b742e636c6f7564646e2e636f6d2f53637265656e25323053686f74253230323031362d31302d31312532306174253230253230504d2e706e67
![gif5新文件](https://user-images.githubusercontent.com/17047142/59908702-97f8e600-9440-11e9-9f7c-cc8b66c70b54.gif)

**Comment by Ccmi** [comment]
MJRefresh：
![54844-26654e03461820f9](https://user-images.githubusercontent.com/17047142/59908919-13f32e00-9441-11e9-888a-b1e5fa8fc25f.gif)
KafkaRefresh：
![gif5新文件](https://user-images.githubusercontent.com/17047142/59908957-2cfbdf00-9441-11e9-948f-481ea5dc7453.gif)

**Comment by rgmyyw** [comment]
问题解决了吗？ 老铁，刷新控件的确有问题啊，这库是不更新了

**Comment by HHHsiang** [comment]
非Swift缘故。只是该控件当初设计时只监控scroll view的content offset。当把scroll enable设置为false时，控件已无法监控到content offset的变化。暂无心力进行升级。
