### ISSUE TITLE
上拉控件一直等待，不走回调

### ISSUE THREAD

**Issue by mocker-f** [HHHsiang/KafkaRefresh#71]
- iOS版本：14.4.2
- KafkaRefresh版本：1.5.0
- 用swift集成使用（每页数据10条）

- 问题描述：正常上拉加载下一页没问题。如果手动下拉刷新后在上拉加载页数会导致控件会一直运行，不走上拉的回调（topicTabel?.bindGlobalStyle(forFootRefreshHandler: ）

- 代码：

        //下拉刷新
        topicTabel?.bindGlobalStyle(forHeadRefreshHandler: { [weak self] in
            self!.topicTabel?.footRefreshControl.endRefreshing()
            self!.nowPage = 1
            self!.getListData(page: 1)
        })
        
        //上拉加载
        topicTabel?.bindGlobalStyle(forFootRefreshHandler: { [weak self] in
            self!.topicTabel?.headRefreshControl.endRefreshing()
            self!.nowPage += 1
            self!.getListData(page: self!.nowPage)
        })

    //调用接口
    func getListData(page: Int) {
        let params: [String: Any] = ["page": page, "list_type": topType!, "label_id": labelIdStr]
        NetWorkTools.shared.requestWith(apiport: API_TopicSocialList, params: params) { [weak self] (requestData) in
            SVProgressHUD.dismiss()
            
            //数据异常
            guard let arrData = requestData as? NSArray else {
                if page != 1 {
                    self!.topicTabel?.footRefreshControl.endRefreshing()
                }else {
                    self!.topicTabel?.headRefreshControl.endRefreshing()
                }
                return
            }
    
            //展示和隐藏缺省
            if arrData.count < 1 && page == 1 {
                self!.nodataView?.isHidden = false
            }else {
                self!.nodataView?.isHidden = true
            }
            
            //是否需要隐藏上拉控件
            if arrData.count < 10 {
                self!.topicTabel?.footRefreshControl.isHidden = true
            } else {
                self!.topicTabel?.footRefreshControl.isHidden = false
            }
            
            //处理数据
            let tableData = NSMutableArray(array: self!.dataArr)
            tableData.addObjects(from: arrData as! [Any])
            if page != 1 {
                self!.topicTabel?.footRefreshControl.endRefreshing()
                self!.dataArr = NSMutableArray(array: tableData)
            } else {
                self!.topicTabel?.headRefreshControl.endRefreshing()
                self!.dataArr = NSMutableArray(array: arrData)
            }
            self!.topicTabel?.reloadData()
            
        } failure: { [weak self] (msg) in
            if page != 1 {
                self!.topicTabel?.footRefreshControl.endRefreshing()
            }else {
                self!.topicTabel?.headRefreshControl.endRefreshing()
            }
            SVProgressHUD.showInfo(withStatus: (msg as! String))
        }
    }

# ☕️  [赞助](https://github.com/OpenFeyn/KafkaRefresh/blob/master/sponsor.jpg)

**Comment by HHHsiang** [comment]
请在隐藏刷新控件前，先调用停止刷新方法
